# Generated by Django 5.2.7 on 2025-10-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('cart', 'Add to Cart'), ('wishlist', 'Add to Wishlist'), ('purchase', 'Purchase'), ('review', 'Review'), ('share', 'Share'), ('search', 'Search Result Click')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('search_query', models.CharField(blank=True, max_length=500)),
                ('referrer_url', models.URLField(blank=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='recommendat_custome_d004fa_idx'), models.Index(fields=['product', 'interaction_type'], name='recommendat_product_6b7760_idx'), models.Index(fields=['session_id', '-created_at'], name='recommendat_session_e7ef13_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('recommendation_type', models.CharField(max_length=50)),
                ('recommended_products', models.JSONField()),
                ('page_type', models.CharField(max_length=50)),
                ('clicked_products', models.JSONField(default=list)),
                ('conversion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', '-created_at'], name='recommendat_custome_5528e9_idx'), models.Index(fields=['session_id', '-created_at'], name='recommendat_session_364686_idx')],
            },
        ),
    ]
